# Generated by Django 3.0.5 on 2021-01-18 18:14

from django.db import migrations, models
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(
                    db_index=True, max_length=254, unique=True,
                    verbose_name='email address')),
                ('role', models.TextField(
                    choices=[('user', 'User'), ('moderator', 'Moderator'),
                             ('admin', 'Admin')], default='user')),
                ('bio', models.TextField(
                    blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['email'],
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
