# Generated by Django 3.0.5 on 2021-01-19 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование категории',
                                          max_length=200,
                                          verbose_name='Название')),
                ('slug', models.SlugField(help_text='Адрес в интернете',
                                          unique=True, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование жанра',
                                          max_length=200,
                                          verbose_name='Название')),
                ('slug', models.SlugField(help_text='Адрес в интернете',
                                          unique=True, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    db_index=True,
                    help_text='Наименование произведения',
                    max_length=100, verbose_name='Название')),
                ('year',
                 models.IntegerField(help_text='Год выпуска',
                                     verbose_name='Год')),
                ('description', models.CharField(
                    blank=True,
                    help_text='Описание произведения',
                    max_length=200, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='titles', to='api.Category')),
                ('genre', models.ManyToManyField(
                    help_text='Жанр произведения',
                    related_name='titles', to='api.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.SmallIntegerField(
                    choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'),
                             (6, '6'), (7, '7'), (8, '8'), (9, '9'),
                             (10, '10')])),
                ('pub_date', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Дата публикации')),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviews', to='api.Title')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(
                    auto_now_add=True,
                    db_index=True,
                    verbose_name='Дата добавления')),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments', to='api.Review')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
