# Generated by Django 3.0.5 on 2021-01-24 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210123_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(
                    0, message=None), django.core.validators.MaxValueValidator(
                    2021, message=None)], verbose_name='Год выпуска'),
        ),
    ]
